import { View, Text, Alert, ScrollView, StyleSheet } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { GlassCard } from '../../src/components/GlassCard';
import { Button } from '../../src/components/Button';
import { generateInvoicePDF } from '../../src/services/PdfService';
import { SafeAreaView } from 'react-native-safe-area-context';
import { LinearGradient } from 'expo-linear-gradient';
import * as Sharing from 'expo-sharing';

export default function QuotePreview() {
  const { id, data } = useLocalSearchParams();
  const router = useRouter();

  let quoteData: any = null;
  try {
    if (data) {
      quoteData = JSON.parse(data as string);
    }
  } catch (e) {
    console.error("Failed to parse quote data");
  }

  const handleGeneratePdf = async () => {
    if (!quoteData) return;
    try {
      const uri = await generateInvoicePDF(
        { client_name: quoteData.client_name },
        quoteData.items,
        quoteData.total,
        quoteData.tax
      );
      
      const isSharingAvailable = await Sharing.isAvailableAsync();
      if (isSharingAvailable) {
        await Sharing.shareAsync(uri, {
          mimeType: 'application/pdf',
          dialogTitle: `Invoice for ${quoteData.client_name}`,
          UTI: 'com.adobe.pdf' // iOS standard identifier for PDFs
        });
      } else {
        Alert.alert("PDF Generated", `Saved to: ${uri}`);
      }
    } catch (e: any) {
      Alert.alert("Error", e.message);
    }
  };

  if (!quoteData) {
    return (
      <View style={{ flex: 1, backgroundColor: '#0F172A', alignItems: 'center', justifyContent: 'center' }}>
        <Text style={{ fontFamily: 'Inter_500Medium', color: '#EF4444' }}>Failed to load quote data</Text>
        <Button variant="primary" title="Go Back" onPress={() => router.back()} style={{ marginTop: 16 }} />
      </View>
    );
  }

  return (
    <View style={{ flex: 1 }}>
      <LinearGradient
        colors={['#1E293B', '#0F172A', '#020617']}
        style={StyleSheet.absoluteFill}
      />
      <SafeAreaView style={{ flex: 1 }} edges={['top']}>
        <ScrollView contentContainerStyle={{ paddingHorizontal: 20, paddingTop: 20, paddingBottom: 120 }}>
          <View style={{ marginBottom: 32 }}>
            <Text style={{ fontFamily: 'Inter_600SemiBold', fontSize: 32, color: '#FFFFFF' }}>Quote Preview</Text>
            <Text style={{ fontFamily: 'Inter_400Regular', fontSize: 16, color: 'rgba(255,255,255,0.7)', marginTop: 8 }}>Generated by AI</Text>
          </View>

          <GlassCard style={{ padding: 24, marginBottom: 32 }}>
            <Text style={{ fontFamily: 'Inter_600SemiBold', fontSize: 20, color: '#FFFFFF', marginBottom: 24 }}>Invoice for {quoteData.client_name}</Text>
            
            {quoteData.debug_transcript && (
              <View style={{ marginBottom: 24, padding: 12, backgroundColor: 'rgba(255,255,255,0.05)', borderRadius: 12 }}>
                <Text style={{ fontFamily: 'Inter_600SemiBold', fontSize: 12, color: 'rgba(255,255,255,0.5)', marginBottom: 4 }}>DEBUG: VAD AI:N HÖRDE:</Text>
                <Text style={{ fontFamily: 'Inter_400Regular', fontSize: 14, color: '#A78BFA', fontStyle: 'italic' }}>"{quoteData.debug_transcript}"</Text>
              </View>
            )}

            {quoteData.items.map((item: any, index: number) => (
              <View key={index} style={{ flexDirection: 'row', justifyContent: 'space-between', marginBottom: 16, paddingBottom: 16, borderBottomWidth: 1, borderBottomColor: 'rgba(255,255,255,0.1)' }}>
                <View>
                  <Text style={{ fontFamily: 'Inter_500Medium', fontSize: 16, color: '#FFFFFF' }}>{item.desc}</Text>
                  <Text style={{ fontFamily: 'Inter_400Regular', fontSize: 14, color: 'rgba(255,255,255,0.7)', marginTop: 4 }}>Qty: {item.qty} x ${item.price}</Text>
                </View>
                <Text style={{ fontFamily: 'Inter_600SemiBold', fontSize: 16, color: '#FFFFFF' }}>${item.qty * item.price}</Text>
              </View>
            ))}

            <View style={{ marginTop: 16, paddingTop: 16 }}>
              <View style={{ flexDirection: 'row', justifyContent: 'space-between', marginBottom: 12 }}>
                <Text style={{ fontFamily: 'Inter_500Medium', fontSize: 16, color: 'rgba(255,255,255,0.7)' }}>Tax</Text>
                <Text style={{ fontFamily: 'Inter_500Medium', fontSize: 16, color: 'rgba(255,255,255,0.7)' }}>${quoteData.tax}</Text>
              </View>
              <View style={{ flexDirection: 'row', justifyContent: 'space-between' }}>
                <Text style={{ fontFamily: 'Inter_700Bold', fontSize: 24, color: '#FFFFFF' }}>Total</Text>
                <Text style={{ fontFamily: 'Inter_700Bold', fontSize: 24, color: '#FFFFFF' }}>${quoteData.total}</Text>
              </View>
            </View>
          </GlassCard>

          <View style={{ flexDirection: 'row', justifyContent: 'space-between' }}>
            <Button variant="secondary" title="Cancel" onPress={() => router.back()} style={{ width: '48%' }} />
            <Button variant="primary" title="Send Invoice" onPress={handleGeneratePdf} style={{ width: '48%' }} />
          </View>
        </ScrollView>
      </SafeAreaView>
    </View>
  );
}
